pipeline {
    agent {
        docker {
            image 'node:8-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        HOME = '.'
        CI = true
        NODE_PATH = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('ESlint') {
            steps {
                sh 'npm run lint'
            }
        }
        stage('Test') {
            steps {
                 sh 'npm test'
            }
        }
    }
}