pipeline {
    agent {
        docker {
            image 'node:8-alpine'
        }
    }
    environment {
        HOME = '.'
        CI = true
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('ESlint') {
            steps {
                sh 'npm run lint'
            }
        }
        stage('Test') {
            steps {
                sh 'printenv'
                sh 'chmod +x ./jenkins/scripts/test.sh'
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}